title: "Back-End Engineering Curriculum - Turing School of Software and Design"
description: "Open source curriculum for the Turing School of Software and Design's back end engineering program."
url: "https://backend.turing.io/"

baseurl: ''
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/assets'

images:
  root_url: '/assets/images'

plugins:
  - jemoji
  - jekyll-algolia

algolia:
  application_id: 'OOLQ64CUYT'
  index_name:     'backend-curriculum-site'
  search_only_api_key: '5b955c38c514d8e5cb906c983c8c24db'
  extensions_to_index: 'html,md'
  nodes_to_index: 'p,li'
  settings:
    attributeForDistinct: 'title'
    distinct: true
  files_to_exclude:
    - _includes
    - _layouts
    - _plugins
    - _sass
    - _site
    - _templates
    - assets
    - public
    - stylesheets
